sudo: false

language: ruby

rvm:
  - 2.4.0

cache: bundler

#script:
#  - bash deploy.sh

deploy:
  provider: pages
  skip_cleanup: true
  local_dir : build
  target_branch : gh-pages
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
